Division function added
Alea237/calculator pull request #3
Opened 2024-11-08 23:50 UTC by Prince-sud0

1. Division function was added
2. Division button was added

2024-11-08 23:54 UTC, Alea237 requested changes
please go through the comment and fix the code!

2024-11-08 23:54 UTC, Alea237 commented on script.js
> +function division() {
please add exrtra line

2024-11-08 23:58 UTC, Prince-sud0 reviewed
fixed as per the request

2024-11-08 23:59 UTC, Alea237 approved these changes

2024-11-09 00:00 UTC, merged

2024-11-09 00:01 UTC, Prince-sud0 commented
Thanks for the Experience Prof.